enum UDKey {
    static let sizeMode = "sizeMode"
    static let anchorPosition = "anchorPosition"
    static let followActiveScreen = "followActiveScreen"
    static let preferredScreen = "preferredScreen"
    static let blurIntensity = "blurIntensity"
    static let backgroundTint = "backgroundTint"
    static let favoriteCaseIDs = "favoriteCaseIDs"
    static let solveHistory = "solveHistory"
    static let myAlgorithms = "myAlgorithms"
    static let wcaInspection = "wcaInspection"
    static let customHotKeyCode = "customHotKeyCode"
    static let customHotKeyMods = "customHotKeyMods"
    static let cubeNotchTrainerStats = "cubeNotchTrainerStats"
    static let cubeNotchSessions = "cubeNotchSessions"
    static let cubeNotchCurrentSession = "cubeNotchCurrentSession"
    static let cubeNotchPersonalBests = "cubeNotchPersonalBests"
    static let cubeNotchLifetimeSolves = "cubeNotchLifetimeSolves"
    static let cubeNotchSolveDates = "cubeNotchSolveDates"
    static let timerPrecision = "timerPrecision"
    static let hideAosDuringSolve = "hideAosDuringSolve"
    static let autoCopyScramble = "autoCopyScramble"
    static let inspectionDuration = "inspectionDuration"
    static let recentCaseIDs = "recentCaseIDs"
    static let pinnedCaseIDs = "pinnedCaseIDs"
    static let selectedAlgorithmIndices = "selectedAlgorithmIndices"
}
